name: Standard Lint

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  standard-lint:
    uses: Typeform/.github/.github/workflows/go-lint-workflow.yaml@v1
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
    with:
      go-version: 1.20.3
